name: flutter_starter
description: A new Flutter project.

version: 2.0.0

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons:
  firebase_core: ^1.0.3
  # firebase_analytics: ^7.1.1 no nullsafe... skip it for now
  firebase_auth: ^1.0.2
  cloud_firestore: ^1.0.4
  speech_to_text: ^5.4.3
  # google_sign_in:
  # apple_sign_in:
  get: ^4.6.1
  get_storage: ^2.0.2
  grouped_list: ^4.2.0
  avatar_glow: ^2.0.2
  crypto: ^3.0.1
  http: ^0.13.4
  csv: ^5.0.0
  dio: ^4.0.4
  shimmer: ^2.0.0
  carousel_slider: ^4.0.0
  fl_chart: ^0.41.0
  sliding_up_panel: ^2.0.0+1
  linked_scroll_controller: ^0.2.0
  youtube_api: ^1.0.4
  blinking_text: ^1.0.1+2
  flutter_switch: ^0.3.2
  kakao_flutter_sdk: ^0.9.0
  flutter_naver_login: ^1.2.4
  url_launcher: ^6.0.20
  youtube_player_flutter: ^8.0.0
  rive: ^0.8.4
  flutter_spinkit: ^5.1.0
  animated_text_kit: ^4.2.1
  toggle_switch: ^2.0.1
  google_fonts: ^2.3.2


dependency_overrides:
 # analyzer: 1.4.0
 # intl: 0.17.0

dev_dependencies:
  

flutter:
  uses-material-design: true
  assets:
    - google_fonts/
    - assets/images/default.png
    - assets/images/defaultDark.png
    - assets/images/model.png
    - assets/images/metaIcon.png
