name: flutter_starter
description: A new Flutter project.

version: 2.0.0

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons:
  firebase_core: ^1.0.3
  # firebase_analytics: ^7.1.1 no nullsafe... skip it for now
  firebase_auth: ^1.0.2
  cloud_firestore: ^1.0.4
  speech_to_text: ^4.2.0
  # google_sign_in:
  # apple_sign_in:
  get: ^4.6.1
  get_storage: ^2.0.2
  avatar_glow: ^2.0.2
  crypto: ^3.0.1
  http: ^0.13.1
  csv: ^5.0.0
  dio: ^4.0.4
  shimmer: ^2.0.0
  carousel_slider: ^4.0.0
  fl_chart: ^0.41.0


dependency_overrides:
 # analyzer: 1.4.0
 # intl: 0.17.0

dev_dependencies:
  

flutter:
  uses-material-design: true
  assets:
    - assets/images/default.png
    - assets/images/defaultDark.png
    - assets/images/model.png
